# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flmnt < Formula
  desc "The developer CLI for the flmnt event-stream memory platform"
  homepage "https://flmnt.dev"
  version "1.10.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v1.10.5/flmnt_1.10.5_darwin_amd64.tar.gz"
      sha256 "be39b2cec00c0ec155ba73bc70377c4a21a2a72b532dd1fdd77d006af3903c10"

      define_method(:install) do
        bin.install "flmnt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v1.10.5/flmnt_1.10.5_darwin_arm64.tar.gz"
      sha256 "90eccd750ccbe415d6c50ae284b104c47d686540ac690299b889b5507536b18a"

      define_method(:install) do
        bin.install "flmnt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v1.10.5/flmnt_1.10.5_linux_amd64.tar.gz"
      sha256 "f4afa3b1d3a365de646de07053350e11144f8e859b98bab972b9e588f081a01c"
      define_method(:install) do
        bin.install "flmnt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v1.10.5/flmnt_1.10.5_linux_arm64.tar.gz"
      sha256 "529e3321a9e15ce35c04de06446fac208b2873a2d58794c05cba8462cde1f9db"
      define_method(:install) do
        bin.install "flmnt"
      end
    end
  end

  test do
    system "#{bin}/flmnt", "version"
  end
end
