# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flmnt < Formula
  desc "The developer CLI for the flmnt event-stream memory platform"
  homepage "https://flmnt.dev"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v0.1.2/flmnt_0.1.2_darwin_amd64.tar.gz"
      sha256 "3d6ddaf42b9b4b6cc777fcb1052a1bfa1e8a5efdc5a3b115aa63526267c6f832"

      define_method(:install) do
        bin.install "flmnt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v0.1.2/flmnt_0.1.2_darwin_arm64.tar.gz"
      sha256 "dbf8a6e39afc2c4645deab02631edf28c2787adb6a5e40893916f46ce27910ac"

      define_method(:install) do
        bin.install "flmnt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v0.1.2/flmnt_0.1.2_linux_amd64.tar.gz"
      sha256 "79fac0c428225f7990358c62530ffb62d1f870d84ed6f1062113ca36e822a621"
      define_method(:install) do
        bin.install "flmnt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmmnt/flmnt-cli/releases/download/v0.1.2/flmnt_0.1.2_linux_arm64.tar.gz"
      sha256 "e88ba1063f167f69b8c60381af18184e684adc8e60b0dd9e2595025f970b6528"
      define_method(:install) do
        bin.install "flmnt"
      end
    end
  end

  test do
    system "#{bin}/flmnt", "version"
  end
end
